-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc junk
profiles['junk'] = S{
    '??? Earring: WAR',
    '??? Earring: MNK',
    '??? Earring: THF',
    '??? Earring: WHM',
    '??? Earring: BLM',
    '??? Earring: RDM',
    '??? Earring: PLD',
    '??? Earring: DRK',
    '??? Earring: DRG',
    '??? Earring: BRD',
    '??? Earring: NIN',
    '??? Earring: SAM',
    '??? Earring: SMN',
    '??? Earring: COR',
    '??? Earring: BLU',
    '??? Earring: PUP',
    '??? Earring: DNC',
    '??? Earring: SCH',
    '??? Earring: GEO',
    '??? Earring: RUN',
    '??? Earring: BST',
    '??? Earring: RNG',
    '2leaf mandra bud',
    '4lf. korrin bud',
    'absorb-attri',
    'acorn',
    'acuex poison',
    'addle',
    'adoulinian kelp',
    'aeroja',
    'Aero V',
    'almond',
    'agility potion',
    'ahriman lens',
    'ahriman tears',
    'airlixir',
    'airlixir +1',
    'airlixir +2',
    'aisha: ichi',
    'amethyst',
    'ametrine',
	'anc. beast horn',
	'animus augeo',
	'animus minuo',
    'antlion jaw',
    'aqua geode',
    'aquamarine',
    'army\'s paeon vi',
    'arrowwood log',
    'ash log',
    'aspir ii',
    'astral signa',
    'auric sand',
    'baramnesra',
    'baramnesia',
    'barnacle',
    'bastore bream',
    'bat fang',
    'bat wing',
    --'beastman blood', //fatso fargann
    'beech log',
    'beetle jaw',
    'beetle shell',
    'behemoth hide',
    'behemoth horn',
    'bhefhel marlin',
    'bird egg',
    'bird feather',
    'black eel',
    'black ghost',
    'black pearl',
    'black prawn',
    'black rock',
    'black sole',
    'blitto needle',
    'blizzard v',
    'blizzara ii',
    'blk. tiger fang',
    'bloodblotch',
    'blue rock',
    'bluetail',
    'bone chip',
    'bone hairpin',
    'boost-agi',
    'boost-chr',
    'boost-dex',
    'boost-int',
    'boost-mnd',
    'boost-str',
    'boyahda moss',
    'brass loach',
    'breeze geode',
    'bugard skin',
    'burst',
    'ca cuong',
    'cactuar needle',
    'cactus arm',
    'cactus stems',
    'carapace gorget',
    'carbite',
    'cerberus hide',
    'cerberus meat',
    'charisma potion',
    'chestnut',
    'chestnut log',
    'chimera blood',
    'chrysoberyl',
    'clear topaz',
    'cobalt jellyfish',
    'colibri beak',
    'colibri feather',
    'comet',
    'cone calamary',
    'contortopus',
    'copper frog',
    'copper ingot',
    'copper ore',
    --'coral fragment',
    'cotton cloth',
    'crab shell',
    'crawler cocoon',
    'crawler egg',
    'crayfish',
    'crescent fish',
    'cure ii',
    'cure iii',
    'cure iv',
    'cure v',
    'cure vi',
    'danceshroom',
    'dark adaman',
    'dark bass',
    'dark crystal',
    'dark fewell',
    'darksteel ingot',
    'darksteel ore',
    'demon horn',
    'dexterity potion',
    'distilled water',
    'dogwood log',
    'doll shard',
    'dragon bone',
    'dragon fruit',
    'dragon heart',
    'dragon meat',
    'dragon talon',
    'dryad root',
    'dst. nugget',
    'durium ore',
    'dwarf remora',
    'earth crystal',
    'earth fewell',
    'eft skin',
    'eggplant',
    'el. pachira fruit',
    'elixir',
    'elm log',
    'elshimo newt',
    'emperor fish',
    'endark',
    'enlight',
    'ether',
    'faerie apple',
    'felicifruit',
    'fenrite',
    'fiendish skin',
    'fira ii',
    'fire carol ii',
    'fire crystal',
    'fire fewell',
    'fire v',
    'fish bones',
    'fish mithkabob',
    'flame blade',
    'flame geode',
    --'fiend blood', //fatso fargann
    'fire fewell',
    'flan meat',
    'flare',
    'flax flower',
    'flint stone',
    'flocon-de-mer',
    'flood',
    'fluorite',
    'flytrap leaf',
    'foe requiem vii',
    'freeze',
    'fresh marjoram',
    'fresh mugwort',
    'fruit seeds',
    'g. bird plume',
    'g. sheep meat',
    'gain-agi',
    'gain-chr',
    'gain-dex',
    'gain-int',
    'gain-mnd',
    'gain-str',
    'garnet',
    'garudite',
    'gavial fish',
    'giant bird fthr.',
    'giant catfish',
    'giant femur',
    'gigant squid',
    'gold carp',
    'gold ore',
    'goshenite',
    'grain seeds',
    'granite',
    'grass thread',
    'green rock',
    'grimmonite',
    'grt. boyahda moss',
    --'guatambu log', item for coalitions
    'gugru tuna',
    'habukatana',
    'hare meat',
    'hecteyes eye',
    'herb seeds',
    'hi-elixir',
    'hi-ether',
    'hi-potion',
    'hi-potion +2',
    'hi-potion +3',
    'h.q. bugard skin',
    'h.q. crab shell',
    'h.q. eft skin',
    'holy ii',
    'holy sword',
    'horde lullaby ii',
    'humus',
    'hydra fang',
    'hydra meat',
    'hydra scale',
    'hyper ether',
    'ice carol ii',
    'ice crystal',
    'ice fewell',
    'ifritite',
    'igneous rock',
    'imp wing',
    'indi-gravity',
    'indi-malaise',
    'indi-vex',
    'indi-wilt',
    'insect wing',
    'int. potion',
    'iron ingot',
    'iron ore',
    'jacaranda log',
    'jadeite',
    'kakka: ichi',
    'kejusu satin',
    'khimaira mane',
    'khroma ore',
    'king locust',
    'king truffle',
    'kitron',
    'kopparnickel ore',
    'lacquer tree log',
    'lamp marimo',
    'land crab meat',
    'lapis lazuli',
    'lesser chigoe',
    'leviatite',
    'light crystal',
    'light fewell',
    'light geode',
    'lightng. crystal',
    'lightning fewell',
    'lithic w. scale',
    'lizard egg',
    'lizard skin',
    'lizard tail',
    'loc. elutriator',
    'lucky egg',
    'lycopodium flower',
    'mackerel',
    'mage\'s ballad iii',
    'magic pot shard',
    'mahogany log',
    'manticore hide',
    'maple log',
    'marble nugget',
    'matamata shell',
    'mercury',
    'meteorite',
    'mind potion',
    'mistletoe',
    'moat carp',
    'moat carp creel',
    'moko grass',
    'mohbwa cloth',
    'moonstone',
    'moorish idol',
    'mushrm. locust',
    'mythril beastcoin',
    'mythril ingot',
    'mythril ore',
    'oak log',
    'painite',
    'pamamas',
    'pea soup',
    'pearl',
    'peiste skin',
    'peiste stinger',
    'peridot',
    'persikos',
    'petrified log',
    'phalanx',
    'phil. stone',
    'phrygian ore',
    'pine nuts',
    'pipira',
    'prize powder',
    'pro-ether',
    'pro-ether +1',
    'protectra iii',
    'protect v',
    'puffball',
    'pugil scales',
    'puk egg',
    'puk wing',
    'purple rock',
    'quake',
    'quus',
    'rabbit hide',
    'ram horn',
    'ram skin',
    'ramuite',
    'raptor skin',
    'red moko grass',
    'red rock',
    'red rose',
    'red terrapin',
    'regen iv',
    'rock salt',
    'rolanberry',
    'rosewood log',
    'rotten meat',
    'ruddy seema',
    'rusty bucket',
    'ruszor meat',
    'san d\'Or. carrot',
    'saffron blossom',
    'saruta cotton',
    'scorpion claw',
    'scorpion shell',
    'senroh sardine',
    'sentinel\'s scherzo',
    'shadow geode',
    'shall shell',
    'sheep tooth',
    'sheepskin',
    'shell v',
    'shivite',
    'shoalweed',
    'silver ingot',
    'silver ore',
    'skull locust',
    'sleepshroom',
    'slime oil',
    --'slug eye', these sell for a lot
    'snapping mole',
    'snoll arm',
    'snow geode',
    'soil geode',
    'sphene',
    'spider web',
    'stone ii',
    'stone v',
    'stonega ii',
    'strength potion',
    'sulfur',
    'sunstone',
    'surma staff',
    'taurus horn',
    'teak log',
    'temper',
    'thunder geode',
    'tiger hide',
    'titanite',
    'tourmaline',
    'translucent rock',
    'treant bulb',
    'tree cuttings',
    'tree saplings',
    'turquoise',
    'twitherym wing',
    'ulbukan lobster',
    'umbril ooze',
    'undead skin',
    'urunday log',
    'valor minuet v',
    --'vanadium ore', use in coalition
    'vegetable seeds',
    'velkk necklace',
    'verboshroom',
    'vitality potion',
    'w. spider\'s web',
    'walnut',
    'walnut log',
    'wamoura hair',
    'water carol ii',
    'water crystal',
    'water fewell',
    'water v',
    'waterja',
    'water lily',
    'white rock',
    'win. tea leaves',
    'wind carol ii',
    'wind crystal',
    'wind fewell',
    'wisteria lumber',
    'woozyshroom',
    'wyvern scales',
    'wyvern skin',
    'wyvern tailskin',
    'x-potion',
    'x-potion +1',
    'x-potion +2',
    'x-potion +3',
    'yagudo cherry',
    'yayinbaligi',
    'yellow rock',
    'yurin: ichi',
    'zaffre yggrete',
    'zebra eel',
    'zinc ore',
    'zircon',
    'zuuxowu grip',
    }

return profiles