-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc junk
profiles['junk'] = S{
    '??? Earring: WAR',
    '??? Earring: MNK',
    '??? Earring: THF',
    '??? Earring: WHM',
    '??? Earring: BLM',
    '??? Earring: RDM',
    '??? Earring: PLD',
    '??? Earring: DRK',
    '??? Earring: DRG',
    '??? Earring: BRD',
    '??? Earring: NIN',
    '??? Earring: SAM',
    '??? Earring: SMN',
    '??? Earring: COR',
    '??? Earring: BLU',
    '??? Earring: PUP',
    '??? Earring: DNC',
    '??? Earring: SCH',
    '??? Earring: GEO',
    '??? Earring: RUN',
    '??? Earring: BST',
    '??? Earring: RNG',
    '2leaf mandra bud',
    '4lf. korrin bud',
    'acorn',
    'acuex poison',
    'adoulinian kelp',
    'almond',
    'airlixir',
    'airlixir +1',
    'airlixir +2',
	'anc. beast horn',
	'animus augeo',
	'animus minuo',
    'aqua geode',
    'aquamarine',
    'arrowwood log',
    'ash log',
    'aspir ii',
    'auric sand',
    'barnacle',
    'bastore bream',
    'bat fang',
    'bat wing',
    --'beastman blood', //fatso fargann
    'beetle jaw',
    'beetle shell',
    'bhefhel marlin',
    'bird egg',
    'bird feather',
    'black eel',
    'black ghost',
    'black prawn',
    'black sole',
    'blizzara ii',
    'blk. tiger fang',
    'bloodblotch',
    'blue rock',
    'bluetail',
    'bone chip',
    'boyahda moss',
    'brass loach',
    'breeze geode',
    'burst',
    'ca cuong',
    'cactuar needle',
    'cactus arm',
    'cactus stems',
    'carbite',
    'cerberus hide',
    'charisma potion',
    'chestnut',
    'chimera blood',
    'chrysoberyl',
    'cobalt jellyfish',
    'colibri beak',
    'colibri feather',
    'cone calamary',
    'contortopus',
    'copper frog',
    'copper ore',
    'coral fragment',
    'cotton cloth',
    'crab shell',
    'crawler cocoon',
    'crawler egg',
    'crayfish',
    'crescent fish',
    'cure ii',
    'cure iii',
    'cure iv',
    'cure v',
    'cure vi',
    'danceshroom',
    'dark adaman',
    'dark bass',
    'dark crystal',
    'darksteel ore',
    'demon horn',
    'distilled water',
    'dogwood log',
    'doll shard',
    'dragon heart',
    'dragon meat',
    'durium ore',
    'dwarf remora',
    'earth crystal',
    'eft skin',
    'el. pachira fruit',
    'elixir',
    'elm log',
    'elshimo newt',
    'emperor fish',
    'ether',
    'faerie apple',
    'felicifruit',
    'fenrite',
    'fire crystal',
    'fish bones',
    'flame geode',
    --'fiend blood', //fatso fargann
    'flare',
    'flax flower',
    'flint stone',
    'flocon-de-mer',
    'flood',
    'fluorite',
    'foe requiem vii',
    'freeze',
    'fresh marjoram',
    'fresh mugwort',
    'g. bird plume',
    'garudite',
    'gavial fish',
    'giant bird fthr.',
    'giant catfish',
    'giant femur',
    'gigant squid',
    'gold carp',
    'grain seeds',
    'grimmonite',
    'grt. boyahda moss',
    --'guatambu log', item for coalitions
    'gugru tuna',
    'hare meat',
    'herb seeds',
    'hi-elixir',
    'hi-ether',
    'hi-potion',
    'h.q. crab shell',
    'h.q. eft skin',
    'horde lullaby ii',
    'humus',
    'hydra fang',
    'hydra scale',
    'hyper ether',
    'ice crystal',
    'ifritite',
    'igneous rock',
    'imp wing',
    'insect wing',
    'jacaranda log',
    'jadeite',
    'kakka: ichi',
    'king locust',
    'king truffle',
    'kitron',
    'lacquer tree log',
    'lamp marimo',
    'land crab meat',
    'lesser chigoe',
    'leviatite',
    'light crystal',
    'light geode',
    'lightng. crystal',
    'lithic w. scale',
    'lizard egg',
    'lizard skin',
    'lizard tail',
    'loc. elutriator',
    'lucky egg',
    'mackerel',
    'magic pot shard',
    'mahogany log',
    'maple log',
    'marble nugget',
    'matamata shell',
    'mercury',
    'moat carp',
    'moat carp creel',
    'moko grass',
    'moonstone',
    'moorish idol',
    'mushrm. locust',
    'mythril beastcoin',
    'mythril ingot',
    'mythril ore',
    'oak log',
    'painite',
    'pamamas',
    'pea soup',
    'peiste skin',
    'peiste stinger',
    'persikos',
    'petrified log',
    'phalanx',
    'phil. stone',
    'phrygian ore',
    'pine nuts',
    'pipira',
    'prize powder',
    'pro-ether',
    'pro-ether +1',
    'pugil scales',
    'quake',
    'quus',
    'rabbit hide',
    'ram horn',
    'ram skin',
    'ramuite',
    'raptor skin',
    'red moko grass',
    'red rock',
    'red rose',
    'red terrapin',
    'rotten meat',
    'rusty bucket',
    'ruszor meat',
    'san d\'Or. carrot',
    'saffron blossom',
    'scorpion claw',
    'scorpion shell',
    'senroh sardine',
    'shadow geode',
    'shall shell',
    'sheep tooth',
    'shivite',
    'shoalweed',
    'silver ore',
    'skull locust',
    --'slug eye', these sell for a lot
    'snapping mole',
    'snoll arm',
    'snow geode',
    'soil geode',
    'spider web',
    'stonega ii',
    'sulfur',
    'sunstone',
    'taurus horn',
    'teak log',
    'thunder geode',
    'titanite',
    'treant bulb',
    'tree cuttings',
    'ulbukan lobster',
    'umbril ooze',
    'urunday log',
    --'vanadium ore', use in coalition
    'vegetable seeds',
    'velkk necklace',
    'verboshroom',
    'vitality potion',
    'w. spider\'s web',
    'walnut',
    'walnut log',
    'water crystal',
    'white rock',
    'wind crystal',
    'wisteria lumber',
    'woozyshroom',
    'wyvern scales',
    'x-potion',
    'x-potion +1',
    'x-potion +2',
    'x-potion +3',
    'yagudo cherry',
    'yayinbaligi',
    'yellow rock',
    'zaffre yggrete',
    'zebra eel',
    'zinc ore',
    'zircon',
    }

return profiles