-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc junk
profiles['junk'] = S{
    '??? Earring: WAR',
    '??? Earring: MNK',
    '??? Earring: THF',
    '??? Earring: WHM',
    '??? Earring: BLM',
    '??? Earring: RDM',
    '??? Earring: PLD',
    '??? Earring: DRK',
    '??? Earring: DRG',
    '??? Earring: BRD',
    '??? Earring: NIN',
    '??? Earring: SAM',
    '??? Earring: SMN',
    '??? Earring: COR',
    '??? Earring: BLU',
    '??? Earring: PUP',
    '??? Earring: DNC',
    '??? Earring: SCH',
    '??? Earring: GEO',
    '??? Earring: RUN',
    '??? Earring: BST',
    '??? Earring: RNG',
    '??? Earring: WAR +1',
    '??? Earring: MNK +1',
    '??? Earring: THF +1',
    '??? Earring: WHM +1',
    '??? Earring: BLM +1',
    '??? Earring: RDM +1',
    '??? Earring: PLD +1',
    '??? Earring: DRK +1',
    '??? Earring: DRG +1',
    '??? Earring: BRD +1',
    '??? Earring: NIN +1',
    '??? Earring: SAM +1',
    '??? Earring: SMN +1',
    '??? Earring: COR +1',
    '??? Earring: BLU +1',
    '??? Earring: PUP +1',
    '??? Earring: DNC +1',
    '??? Earring: SCH +1',
    '??? Earring: GEO +1',
    '??? Earring: RUN +1',
    '??? Earring: BST +1',
    '??? Earring: RNG +1',
    '2leaf mandra bud',
    '4lf. korrin bud',
    'a. ygg. shard i',
    'a. ygg. shard ii',
    'a. ygg. shard iii',
    'a. ygg. shard iv',
    'a. ygg. shard v',
    'absorb-attri',
    'acorn',
    'acuex poison',
    'addle',
    'adoulinian kelp',
    'aeroja',
    'Aero V',
    'almond',
    'agility potion',
    'ahriman lens',
    'ahriman tears',
    'aht urhgan brass',
    'airlixir',
    'airlixir +1',
    'airlixir +2',
    'aisha: ichi',
    'akaso',
    'amethyst',
    'ametrine',
	'anc. beast horn',
    'ancient salt',
    'angel skin',
	'animus augeo',
	'animus minuo',
    'antlion jaw',
    'apkallu feather',
    'apple juice',
    'aqua geode',
    'aquamarine',
    'army\'s paeon vi',
    'arrabbiata',
    'arrowwood log',
    'ash log',
    'ash staff',
    'aspir ii',
    'astral signa',
    'auric sand',
    'baramnesra',
    'baramnesia',
    'barnacle',
    'bastore bream',
    'bat fang',
    'bat wing',
    'beastman blood',
    'beech log',
    'beehive chip',
    'beetle jaw',
    'beetle shell',
    'behemoth hide',
    'behemoth horn',
    'bhefhel marlin',
    'bird egg',
    'bird feather',
    'black eel',
    'black ghost',
    'black pearl',
    'black prawn',
    'black rock',
    'black sole',
    'blitto needle',
    'blizzaja',
    'blizzard',
    'blizzard ii',
    'blizzard iii',
    'blizzard iv',
    'blizzard v',
    'blk. tiger fang',
    'bloodblotch',
    'blue rock',
    'bluetail',
    'bomb ash',
    'bone chip',
    'bone hairpin',
    'boost-agi',
    'boost-chr',
    'boost-dex',
    'boost-int',
    'boost-mnd',
    'boost-str',
    'boyahda moss',
    'brass loach',
    'breeze geode',
    'broiled eel',
    'bugard skin',
    'bugard tusk',
    'burst',
    'ca cuong',
    'cactuar needle',
    'cactus arm',
    'cactus stems',
    'cambric',
    'carapace gorget',
    'carbite',
    'celadon yggrete',
    'cerberus hide',
    'cerberus meat',
    'chapuli horn',
    'chapuli wing',
    'charisma potion',
    'chestnut',
    'chestnut log',
    'chimera blood',
    'chocobo fthr.',
    'chrysoberyl',
    'clear topaz',
    'cobalt jellyfish',
    'cockatrice meat',
    'cockatrice skin',
    'coeurl hide',
    'coeurl meat',
    'colibri beak',
    'colibri feather',
    'comet',
    'cone calamary',
    'contortopus',
    'copper frog',
    'copper ingot',
    'copper ore',
    --'coral fragment',
    'cotton cloth',
    'crab shell',
    'craklaw pincer',
    'crawler cocoon',
    'crawler egg',
    'crayfish',
    'crescent fish',
    'cure ii',
    'cure iii',
    'cure iv',
    'cure v',
    'cure vi',
    'dahlia',
    'danceshroom',
    'dark adaman',
    'dark bass',
    'dark carol',
    'dark carol ii',
    'dark crystal',
    'dark fewell',
    'darksteel ingot',
    'darksteel ore',
    'demon horn',
    'demon skull',
    'dexterity potion',
    'diamond',
    'distilled water',
    'divine log',
    'dogwood log',
    'doll shard',
    'dragon bone',
    'dragon fruit',
    'dragon heart',
    'dragon meat',
    'dragon talon',
    'dryad root',
    'dst. nugget',
    'durium ore',
    'dwarf remora',
    'earth crystal',
    'earth fewell',
    'earth spirit',
    'eft skin',
    'eggplant',
    'el. pachira fruit',
    'elixir',
    'elm log',
    'elshimo newt',
    'emerald',
    'emperor fish',
    'endark',
    'enlight',
    'ether',
    'eudaemon blade',
    'eudaemon cape',
    'eudaemon sash',
    'eudaemon shld.',
    'faerie apple',
    'faithful\'s legs i',
    'faithful\'s legs ii',
    'faithful\'s legs iii',
    'faithful\'s legs iv',
    'faithful\'s legs v',
    'faithfl. torso iv',
    'felicifruit',
    'fenrite',
    'fiendish skin',
    'fira ii',
    'fire carol ii',
    'fire crystal',
    'fire fewell',
    'fire v',
    'fish bones',
    'fish mithkabob',
    'flame blade',
    'flame geode',
    'fiend blood',
    'fire fewell',
    'flan meat',
    'flare',
    'flax flower',
    'flint stone',
    'flocon-de-mer',
    'flood',
    'fluorite',
    'flytrap leaf',
    'foe requiem vii',
    'freeze',
    'fresh marjoram',
    'fresh mugwort',
    'fruit seeds',
    'g. bird plume',
    'g. sheep meat',
    'gain-agi',
    'gain-chr',
    'gain-dex',
    'gain-int',
    'gain-mnd',
    'gain-str',
    'galkan sausage',
    'garnet',
    'garudite',
    'gavial fish',
    'giant bird fthr.',
    'giant catfish',
    'giant femur',
    'giant stinger',
    'gigant squid',
    'gnat wing',
    'gold carp',
    'gold ore',
    'goshenite',
    'grain seeds',
    'granite',
    'grass thread',
    'green rock',
    'grimmonite',
    'grt. boyahda moss',
    'guatambu log',
    'gugru tuna',
    'habukatana',
    'hare meat',
    'hecteyes eye',
    'hemlock',
    'herb seeds',
    'hi-elixir',
    'hi-ether',
    'hi-potion',
    'hi-potion +2',
    'hi-potion +3',
    'h.q. bugard skin',
    'h.q. crab shell',
    'h.q. eft skin',
    'holy ii',
    'holy sword',
    'honey',
    'horde lullaby ii',
    'humus',
    'hydra fang',
    'hydra meat',
    'hydra scale',
    'hyper ether',
    'ice carol ii',
    'ice crystal',
    'ice fewell',
    'ifritite',
    'igneous rock',
    'imp wing',
    'indi-gravity',
    'indi-malaise',
    'indi-paralysis',
    'indi-vex',
    'indi-wilt',
    'insect wing',
    'int. potion',
    'iron ingot',
    'iron ore',
    'iron sand',
    'jacaranda log',
    'jadeite',
    'kakka: ichi',
    'kejusu satin',
    'khimaira mane',
    'khroma ore',
    'king locust',
    'king truffle',
    'kitron',
    'kopparnickel ore',
    'lacquer tree log',
    'lamp marimo',
    'land crab meat',
    'lapis lazuli',
    'lauan log',
    'lesser chigoe',
    'leviatite',
    'light carol',
    'light carol ii',
    'light crystal',
    'light fewell',
    'light geode',
    'lightng. crystal',
    'lightning fewell',
    'lithic w. scale',
    'little worm',
    'lizard egg',
    'lizard skin',
    'lizard tail',
    'loc. elutriator',
    'lucky egg',
    'lustreless wing',
    'lycopodium flower',
    'mackerel',
    'mage\'s ballad iii',
    'magic pot shard',
    'mahogany log',
    'manticore hide',
    'maple log',
    'marble nugget',
    'marguerite',
    'matamata shell',
    'mercury',
    'meteorite',
    'mind potion',
    'mistletoe',
    'moat carp',
    'moat carp creel',
    'moko grass',
    'mohbwa cloth',
    'moonstone',
    'moorish idol',
    'mushrm. locust',
    'mythril beastcoin',
    'mythril ingot',
    'mythril ore',
    'oak log',
    'old case',
    'orobon meat',
    'p. ygg. shard i',
    'p. ygg. shard ii',
    'p. ygg. shard iii',
    'p. ygg. shard iv',
    'p. ygg. shard v',
    'painite',
    'pamamas',
    'pea soup',
    'peapuk wing',
    'pearl',
    'pebble',
    'peiste skin',
    'peiste stinger',
    'peridot',
    'persikos',
    'petrified log',
    'phalanx',
    'phil. stone',
    'phlox yggrete',
    'phrygian ore',
    'pine nuts',
    'pipira',
    'prize powder',
    'pro-ether',
    'pro-ether +1',
    'protectra iii',
    'protect v',
    'puffball',
    'pugil scales',
    'puk egg',
    'puk wing',
    'purple rock',
    'quake',
    'quus',
    'raaz hide',
    'raaz tusk',
    'rabbit hide',
    'ra\'ka. visage i',
    'rala visage i',
    'rala visage ii',
    'rala visage iii',
    'rala visage iv',
    'rala visage v',
    'ram horn',
    'ram skin',
    'ramuite',
    'raptor skin',
    'red moko grass',
    'red rock',
    'red rose',
    'red terrapin',
    'refractive crystal',
    'regen iv',
    'revival root',
    'rock salt',
    'rolanberry',
    'rosewood log',
    'rotten meat',
    'ruddy seema',
    'rusty bucket',
    'ruszor meat',
    'san d\'Or. carrot',
    'saffron blossom',
    'saruta cotton',
    'scorpion claw',
    'scorpion shell',
    'senroh sardine',
    'sentinel\'s scherzo',
    'shadow geode',
    'shall shell',
    'sheep leather',
    'sheep tooth',
    'sheepskin',
    'shell v',
    'shivite',
    'shoalweed',
    'silk thread',
    'silver ingot',
    'silver ore',
    'skull locust',
    'sleepshroom',
    'slime oil',
    --'slug eye', these sell for a lot
    'snap. secretion',
    'snap. tendril',
    'sneak',
    'snapping mole',
    'snoll arm',
    'snow geode',
    'soil geode',
    'sphene',
    'spider web',
    'stone ii',
    'stone v',
    'stonega ii',
    'strength potion',
    'sulfur',
    'sunstone',
    'surma staff',
    'taurus horn',
    'taurus wing',
    'teak log',
    'temper',
    "thu'ban's scale",
    'thundaja',
    'thundaga',
    'thundaga ii',
    'thundaga iii',
    'thunder geode',
    'thunder',
    'thunder ii',
    'thunder iii',
    'thunder iv',
    'thunder v',
    'tiger hide',
    'titanite',
    'titanium ore',
    'tourmaline',
    'translucent rock',
    'treant bulb',
    'tree cuttings',
    'tree saplings',
    'tulfaire feather',
    'turquoise',
    'twitherym wing',
    'ulbukan lobster',
    'umbril ooze',
    'undead skin',
    'urunday log',
    'valor minuet v',
    --'vanadium ore', use in coalition
    'vegetable seeds',
    'velkk mask',
    'velkk necklace',
    'verboshroom',
    'vitality potion',
    'voay staff -1',
    'voay sword -1',
    'w. spider\'s web',
    'walnut',
    'walnut log',
    'wamoura hair',
    'water carol ii',
    'water crystal',
    'water fewell',
    'water v',
    'waterja',
    'water lily',
    'white rock',
    'win. tea leaves',
    'wijnruit',
    'wind carol ii',
    'wind crystal',
    'wind fewell',
    'wisteria lumber',
    'woozyshroom',
    'wivre hide',
    'wivre horn',
    'wivre maul',
    'wyvern scales',
    'wyvern skin',
    'wyvern tailskin',
    'x-potion',
    'x-potion +1',
    'x-potion +2',
    'x-potion +3',
    'yagudo cherry',
    'yayinbaligi',
    'yellow rock',
    'yorchete',
    'yorcia visage i',
    'yorcia visage ii',
    'yorcia visage iii',
    'yorcia visage iv',
    'yorcia visage v',
    'yurin: ichi',
    'z. ygg. shard i',
    'z. ygg. shard ii',
    'z. ygg. shard iii',
    'z. ygg. shard iv',
    'z. ygg. shard v',
    'zaffre yggrete',
    'zebra eel',
    'zinc ore',
    'zircon',
    'zuuxowu grip',
    }

return profiles